import type { EditorSessionPreview, GameClue } from "@/api/game.contracts";
export function sessionFixture(): EditorSessionPreview {
  const clue = (
    id: string,
    trigger: GameClue["trigger"],
    sessionLevel = "",
    source: GameClue["source"] = "session",
  ): GameClue => ({
    id,
    definitionId: id,
    trigger,
    sessionLevel,
    source,
    question: source === "question" ? "q1" : "",
    kind: "text",
    position: 0,
    narrative: "",
    autoPlay: true,
    unlockedAt: "",
    content: {
      title: id,
      text: `${id} 正文`,
      url: "",
      imageUrls: [],
      buttonText: "查看",
    },
  });
  return {
    issues: [],
    narratives: [
      {
        id: "story",
        kind: "letter",
        title: "通关来信",
        payload: {
          variant: "modern",
          hintText: "开启来信",
          paragraphs: [
            { content: "通关剧情正文。", delayMs: 0, align: "left" },
          ],
          backgroundImages: [],
          typingSpeedMs: 60,
        },
      },
    ],
    assignment: {
      id: "editor-session",
      session: "editor-session",
      player: "editor-player",
      status: "assigned",
      order: 0,
      startsAt: "",
      endsAt: "",
      startedAt: "",
      completedAt: "",
      previousAssignment: "",
      title: "测试场次",
      description: "入场说明",
      minLevel: 1,
      maxLevel: null,
      completedLevels: 0,
      totalLevels: 2,
      presentation: { completionStyle: "finale" },
      completionTarget: { kind: "narrative", id: "story" },
      currentIndex: 0,
      serverTime: "2026-01-01T00:00:00.000Z",
      levels: [0, 1].map((i) => ({
        id: `l${i + 1}`,
        position: i,
        xp: 10,
        autoNext: true,
        completedAt: "",
        wrongCount: 0,
        cooldownUntil: "",
        locked: false,
        presentationOverride: {},
        lastAnswer: "",
        question: {
          id: `q${i + 1}`,
          kind: "text",
          title: `题目${i + 1}`,
          placeholder: "输入答案",
          content: [
            {
              text: `第${i + 1}关正文`,
              hint: "",
              imageUrl: "",
              imageUrls: [],
              videoUrl: "",
            },
          ],
          options: [],
        },
      })),
      clues: [
        clue("开场线索", "start"),
        clue("过关线索", "level_completed", "l1"),
        clue("通用线索", "question_completed", "l1", "question"),
        clue("手动线索", "manual"),
        clue("终局线索", "session_completed"),
        {
          ...clue("剧情线索", "level_completed", "l2"),
          kind: "letter",
          narrative: "story",
          autoPlay: false,
        },
      ],
    },
  };
}
